# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b65fc348ab0f4ab08da6437ef5a4861f79c9229b740c3c303c40cc1cba190ccfce253f478f1fbca43c0eee046c395a18a801e182762ddee72466948c619b0526

test:
  secret_key_base: a20b1b3655b14b64a7704accb5f20d439d8761f9fe093bbd588e0895f15a6d242c453942b616f807bacfef3fe741bc797f15ae30eb85b7069a785a5c1356434b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
